name: Build and deploy ASP.Net Core app to Azure Web App - unimate

on:
    push:
        branches:
            - dev
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: List directory structure
              run: ls -R
              working-directory: ./

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.x"

            - name: Restore dependencies
              run: dotnet restore Unimate2/Unimate2.csproj
              working-directory: ./

            - name: Build with dotnet
              run: dotnet build Unimate2/Unimate2.csproj --configuration Release --no-restore
              working-directory: ./

            - name: Publish Unimate2
              run: dotnet publish Unimate2/Unimate2.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
              working-directory: ./

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: .net-app
                  path: ${{env.DOTNET_ROOT}}/myapp

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: .net-app

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56A37CF047D446D4AF6688E824F4516D }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DD3A399CE3924E7589C6C7144B20A9C7 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ED4A396547A8454499AC8C865D2DD395 }}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "unimate"
                  slot-name: "Production"
                  package: .
